### ISSUE TITLE
padding / margin not provided with fallback?

### ISSUE THREAD

**Issue by phonoloop** [pierreburel/sass-rem#1]
I cannot get fallbacks for padding/margin.

Example:
+rem((font-size: 22px, padding: 9px 6px 4px))

Output:
Font-size is ok but padding only gives rem values.

Maybe it's because i'm using the Sass syntax and not SCSS?

**Comment by pierreburel** [comment]
Hi!

I don't use the .sass syntax, but I just tested with Sass 3.4.13 and I have no issues : https://gist.github.com/pierreburel/69b5c566280af10fef9d

What do you use to compile your .sass files ?

**Comment by phonoloop** [comment]
Hi Pierre

Your code is working perfectly indeed. 
I've tested my code in Sassmeister and had not issues at all.
Only when compiling with Gulp it seems to remove the px values for padding and margin.
I guess I need  to recheck my script.

Thanks for your time. :-)

**Comment by pierreburel** [comment]
I just tested with Gulp and node-sass/libsass and still no issues : https://gist.github.com/pierreburel/69b5c566280af10fef9d

Really strange, maybe you have another Gulp task(s) removing/cleaning some stuff?

**Comment by phonoloop** [comment]
Yes, I do have some other tasks running.
The only thing I've noticed is that you're using gulp-sass while i'm using gulp-ruby-sass.
The reason why I use the ruby version is because of autoprefixer. 

All these automation tools are great as long as those packages work together. But when they don't, a real pain in the butt if you ask me. :-)

**Comment by pierreburel** [comment]
If you use the Ruby version of Sass just for Autoprefixer, you should totally use it directly with gulp-postcss (https://github.com/postcss/autoprefixer#gulp) so you can use LibSass, which is way faster.

Closing the ticket for now, and thanks for using sass-rem !

**Comment by pierreburel** [comment]
Here's just an example of a really simple gulpfile with sass and autoprefixer:

```
var gulp = require('gulp');
var sass = require('gulp-sass');
var postcss = require('gulp-postcss');
var autoprefixer = require('autoprefixer-core');

gulp.task('default', function () {
  gulp.src('./*.sass')
      .pipe(sass({indentedSyntax: true}))
      .pipe(postcss([ autoprefixer({ browsers: ['last 2 version'] }) ]))
      .pipe(gulp.dest('./'));
});
```

**Comment by pierreburel** [comment]
Just an update since someone reported the same problem: sounds like a gulp-minify-css/clean-css issue, cf. https://github.com/murphydanger/gulp-minify-css/issues/46
See `advanced` and `compatibility` options : https://github.com/jakubpawlowicz/clean-css#how-to-set-compatibility-mode
