### ISSUE TITLE
Doesn't work with node-sass >= 4.8.0

### ISSUE THREAD

**Issue by sqal** [pierreburel/sass-rem#10]
I just upgraded node-sass in my project to version 4.8.1 and sass-rem doesn't work correctly anymore. It  continues to convert values from rem to px, but doesn't add rem units, example:

```
font-size: rem(16px); // -> font-size: 1;
```

informations about my environment:

| software         | version
| ---------------- | -------
| sass-rem   |  2.0.0
| node-sass | 4.8.1
| node             | 9.6.1
| Operating System | Windows 10 x64

**Comment by pierreburel** [comment]
Good catch, there was an incompatibility with LibSass 3.5 released last week : I shipped 2.0.1 with a fix, it should works now.
Thanks for your report !

**Comment by sqal** [comment]
Yes everything works now 👍  Thank you so much for this super quick fix :)
