### ISSUE TITLE
JS Option

### ISSUE THREAD

**Issue by jimthedev** [pierreburel/sass-rem#11]
Hey there,

Thanks for this library. Would you consider adding a JavaScript option to perform the same transformation? It would be helpful given that we have some teams using SASS, some using postcss, some using css in js, etc and having them using the same lib would be good peace of mind. 

Thoughts?

Thanks!

Jim

**Comment by pierreburel** [comment]
Hi,

I had a PostCSS version in the works for a long time actually. Just finished it and published it on NPM : https://www.npmjs.com/package/postcss-rem

It's my first PostCSS plugin and I havn't tested it in production yet, so if you use it don't hesitate to open issues on its repo if there is any problem : https://github.com/pierreburel/postcss-rem

Note that there is [some other PostCSS plugins](https://github.com/cuth/postcss-pxtorem) for rem conversion, but they usually change px values directly without using a function, so it really depends of your usage. 

Pierre
