### ISSUE TITLE
v3.0.0 doesn't work with node-sass 6.0.1 on Windows 10

### ISSUE THREAD

**Issue by luigicut** [pierreburel/sass-rem#15]
Hello,
I was setting up a new project on my Windows 10 machine and, by installing the newest version of the library, the browser wasn't able to recognize the function rem(16px) as a rem value.
By installing the previous version 2.0.1 worked fine.

**Comment by pierreburel** [comment]
v3.x only supports Dart Sass (or just Sass), which is the recommended version by Sass team as LibSass (used by node-sass) and Ruby Sass are deprecated. 

As said in the README, you can stay on 2.x if you want to use those Sass compilers (the only new feature of v3.x is [Sass Module](https://sass-lang.com/blog/the-module-system-is-launched)).
