### ISSUE TITLE
Question regarding $rem-baseline

### ISSUE THREAD

**Issue by MarkBatchelder** [pierreburel/sass-rem#3]
I'm new to SASS mixins and wanted to verify that if I'm using a 16px default font size, that I can just change $rem-baseline to 16 and everything will work the same.

**Comment by pierreburel** [comment]
Hi,

you can set `$rem-baseline: 16px;`, drop the `html { font-size: 62.5%; }` and the mixin/function will calculate rem values and px fallbacks.

I added more documentation regarding this variable : https://github.com/pierreburel/sass-rem#changing-baseline

**Comment by MarkBatchelder** [comment]
Awesome, this will be a big improvement over the mixin I've been using, and love that it's LibSASS compatible.
