### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by mmjaeger** [pierreburel/sass-rem#4]
Hello
Hope you got a minute to help - I've no idea what I'm doing wrong - in one of my sass files, I've the following code:

`.test{
    @include rem(width, 40px);
    height: rem(80px);
 }`

what I get in the css file is:
`.test{
    width: 4rem;
    height: 5rem;
 }`

base is set to 10 px so the width is correct - the height is calculated based on 16px - do you have any idea why this is happening?

Thanks

**Comment by pierreburel** [comment]
Hi!
Could you give me more info on how you compile your .scss? Do you use LibSass or Ruby Sass, and which version? Any other post-processing stuff, like minifying?

**Comment by mmjaeger** [comment]
Hello Pierre
I think I figured out what the issue is - if I import your rem mixin before
Bourbon it creates those issues - if I change the import order, it seems to
work fine - Bourbon has also a function called rem.

On Tue, Sep 15, 2015 at 5:45 AM, Pierre Burel notifications@github.com
wrote:

> Hi!
> Could you give me more info on how you compile your .scss? Do you use
> LibSass or Ruby Sass and which version? Any other post-processing stuff,
> like minifying?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pierreburel/sass-rem/issues/4#issuecomment-140375970.

## 

Marco M. Jaeger
http://net4visions.com

**Comment by mmjaeger** [comment]
Still kind of struggling with the following code - hope you can provide
some insight:

`
$grid-gutter-width: rem(40px);

@mixin make-container($gutter: $grid-gutter-width) {
  margin-right: auto;
  margin-left: auto;
  padding-left:  ($gutter / 2);
  padding-right: ($gutter / 2);
  @if $enable-flex {
  } @else {
    @include clearfix();
  }
}`

if I set the grid-gutter like: `$grid-gutter-width: rem(40px);` the css
shows 4rem/2 instead of the expected 2rem - if I set the grid-gutter to
`4rem` everything works fine?

any idea what I'm doing wrong?

thank you again for your input.

On Tue, Sep 15, 2015 at 7:11 AM, Marco M. Jaeger mmjaeger@gmail.com wrote:

> Hello Pierre
> I think I figured out what the issue is - if I import your rem mixin
> before Bourbon it creates those issues - if I change the import order, it
> seems to work fine - Bourbon has also a function called rem.
> 
> On Tue, Sep 15, 2015 at 5:45 AM, Pierre Burel notifications@github.com
> wrote:
> 
> > Hi!
> > Could you give me more info on how you compile your .scss? Do you use
> > LibSass or Ruby Sass and which version? Any other post-processing stuff,
> > like minifying?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/pierreburel/sass-rem/issues/4#issuecomment-140375970
> > .
> 
> ## 
> 
> Marco M. Jaeger
> http://net4visions.com

## 

Marco M. Jaeger
http://net4visions.com

**Comment by pierreburel** [comment]
Interesting find. I would advise you to make your operations before converting (`padding-left: rem($gutter / 2);`), however i made a small change: now the `rem` function return a number instead of a list if possible.

**Comment by mmjaeger** [comment]
I'll give it a try, thank you

On Wed, Sep 16, 2015 at 11:34 AM, Pierre Burel notifications@github.com
wrote:

> Interesting find. I would advise you to make your operations before
> converting (padding-left: rem($gutter / 2);), however i made a small
> change: now the rem function return a number instead of a list if
> possible.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pierreburel/sass-rem/issues/4#issuecomment-140835853.

## 

Marco M. Jaeger
http://net4visions.com

**Comment by mmjaeger** [comment]
That did the trick - thanks again

On Wed, Sep 16, 2015 at 12:10 PM, Marco M. Jaeger mmjaeger@gmail.com
wrote:

> I'll give it a try, thank you
> 
> On Wed, Sep 16, 2015 at 11:34 AM, Pierre Burel notifications@github.com
> wrote:
> 
> > Interesting find. I would advise you to make your operations before
> > converting (padding-left: rem($gutter / 2);), however i made a small
> > change: now the rem function return a number instead of a list if
> > possible.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/pierreburel/sass-rem/issues/4#issuecomment-140835853
> > .
> 
> ## 
> 
> Marco M. Jaeger
> http://net4visions.com

## 

Marco M. Jaeger
http://net4visions.com
