### ISSUE TITLE
weird issue

### ISSUE THREAD

**Issue by mmjaeger** [pierreburel/sass-rem#5]
Hello
I got the following code - baseline is set to 10px:
`a {

```
        background-color: #fff;
        border: 1px solid #eee;
        border-top: 0;
    font-size: rem(14px);
   @include rem(font-size, 14px);
        padding: rem(20px);
        position: relative;
        width: 200px;
        word-wrap: break-word;

    }`
```

using the rem function returns 0.875rem whereas using the mixin returns 1.4rem which is correct - do you have any ideas what could cause this?

Thanks

**Comment by pierreburel** [comment]
Hi,

I think it's the same issue as #4: if you're using an other lib like Bourbon, you need to import sass-rem after it to overwrite their rem function or mixin.

You have 2 different values because the sass-rem mixin uses a 10px baseline by default and the Bourbon rem function uses a 16px one.
