### ISSUE TITLE
@mixin not working with autoprefixer v7.1.6

### ISSUE THREAD

**Issue by RahulMoral** [pierreburel/sass-rem#9]
`_rem.scss` `@mixin` not working with `autoprefixer v7.1.6`. But it work with `autoprefixer v7.1.5`. 
Please check the link `error`: http://prntscr.com/hebaqx

**Comment by pierreburel** [comment]
Hi,
mh strange, I can't see how it's related with autoprefixer since it works on the compiled code. 
Are you sure that you're importing the lib properly ?

**Comment by pierreburel** [comment]
I guess you sorted it out.

**Comment by RahulMoral** [comment]
It's fix. Thanks.
